[package]
name = "advent-of-code-2023"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
indexmap = "2.1.0"
sugar = { path = "../sugar" }
