[package]
name = "advent-of-code-2015"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
itertools = "0.12.0"
md5 = "0.7.0"
